rules:
  - name: FILES
    condition: .*/runtime/.*lib.rs
    check_type: changed_files
    any:
      - min_approvals: 1
        users:
      - min_approvals: 1
        teams:
          - substrateteamleads
