[package]
name = "substrate-frame-rpc-support"
version = "3.0.0"
authors = [
    "Parity Technologies <admin@parity.io>",
    "Andrew Dirksen <andrew@dirksen.com>",
]
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"
description = "Substrate RPC for FRAME's support"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.16"
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee", rev = "0e46b5cea9cd632dc438a005c77bbaa5c2af562f", features = ["jsonrpsee-types"] }
codec = { package = "parity-scale-codec", version = "2.0.0" }
serde = "1"
frame-support = { version = "4.0.0-dev", path = "../../../../frame/support" }
sp-storage = { version = "4.0.0-dev", path = "../../../../primitives/storage" }
sc-rpc-api = { version = "0.10.0-dev", path = "../../../../client/rpc-api" }

[dev-dependencies]
frame-system = { version = "4.0.0-dev", path = "../../../../frame/system" }
scale-info = "1.0"
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee", rev = "0e46b5cea9cd632dc438a005c77bbaa5c2af562f", features = ["ws-client", "jsonrpsee-types"] }
tokio = { version = "1.13", features = ["macros"] }
