[package]
name = "sc-executor-common"
version = "0.9.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "A set of common definitions that are needed for defining execution engines."
documentation = "https://docs.rs/sc-executor-common/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
derive_more = "0.99.2"
parity-wasm = "0.41.0"
codec = { package = "parity-scale-codec", version = "2.0.0" }
wasmi = "0.6.2"
sp-core = { version = "3.0.0", path = "../../../primitives/core" }
sp-allocator = { version = "3.0.0", path = "../../../primitives/allocator" }
sp-wasm-interface = { version = "3.0.0", path = "../../../primitives/wasm-interface" }
sp-serializer = { version = "3.0.0", path = "../../../primitives/serializer" }
wasmtime = { git = "https://github.com/Vurich/wasmtime.git", branch="master" }

wasmer = "1.0"
wasmer-compiler-singlepass = "1.0"
# wasmer = { git = "https://github.com/0x7CFE/wasmer", branch = "frame-info-patch" }
# wasmer-compiler-singlepass = { git = "https://github.com/0x7CFE/wasmer", branch = "frame-info-patch" }
#wasmer-engine-jit = { git = "https://github.com/0x7CFE/wasmer", branch = "frame-info-patch" }

#wasmer = "1.0.0-alpha3"
#wasmer-compiler-singlepass = "1.0.0-alpha3"
#wasmer-engine-jit = "1.0.0-alpha3"
#wasmer-runtime = "0.17"

thiserror = "1.0.21"

[features]
default = []
