# This file is part of Substrate.
#
# Copyright (C) 2019-2021  Parity Technologies (UK) Ltd.
# SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: continuous-integration

on:
  pull_request:
  push:
    # Running the CI on the master branch is important in order to fill the
    # caches that pull requests will pick up.
    branches:
      - master
jobs:
  test:
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Install dependencies
        run: apt-get install -y clang libssl-dev pkg-config git-restore-mtime
        # run: sudo apt-get install -y clang libssl-dev pkg-config git-restore-mtime

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-11-08
          target: wasm32-unknown-unknown

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      # this is needed to make sure that cargo uses the cached target files,
      # which will have an older date than the checked out source code.
      - name: Restore files timestamps
        run: |
          # set all dirs and files mtime to the fixed timestamp, this one was chosen
          # symbolically as polkadot genesis block date
          find . -exec touch -t 202005260100 {} +
          # restore mtime based on git commit log
          git restore-mtime

      - name: Setup caching for rust/cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo test suite
        run: cargo test --workspace --locked --release --verbose
        env:
          RUSTFLAGS: "-Cdebug-assertions=y -Dwarnings"
          RUST_BACKTRACE: 1
