name: 'Monthly pre-release'
on: ['push']

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Build Changelog"
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        fromTag: "release"
        configuration: ".maintain/github/changelog-configuration.json"
