name: Check reviews

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - reopened
      - synchronize
      - review_requested
      - review_request_removed
  pull_request_review:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pr-custom-review
        uses: paritytech/pr-custom-review@v1
        with:
          token: ${{ secrets.PRCR_TOKEN }}
          locks-review-team: non-parity-devs
          team-leads-team: substrateteamleads
          action-review-team: ci
